// Boteco ACIA 2026 — casas participantes
//
// FONTE: Ficha de Inscrição (respostas do formulário). Textos, endereços,
// bairros e pratos vêm da ficha, sem correção.
//
// EXCEÇÕES, todas anotadas por casa:
//  - lat/lng: a ficha não coleta coordenadas. Vieram do Google a partir do
//    endereço declarado. Conferidas uma a uma.
//  - categoria: não existe na ficha. Inferida do tipo de estabelecimento.
//  - slug: definido aqui. NÃO ALTERAR depois de gerar os QR codes.
//
// PENDÊNCIAS PARA A REUNIÃO COM A ACIA (marcadas com TODO no código):
//  - Cia Petiscaria está sem bairro na ficha.
//  - Garapeira e Caravellas ainda não confirmaram o prato.
//  - A ficha não coleta horário de funcionamento. Falta para o site
//    e será necessário depois para a janela de aceitação de voto.
//  - Divergências de número/endereço entre ficha e Google (Império,
//    Buteco F.N.M) foram mantidas como na ficha.

export const restaurantes = [
  {
    slug: "garapeira-gastronomia",
    nome: "Garapeira Gastronomia",
    prato: "Bolinho de Pirarucu com jambu", // TODO: ficha marca "ainda vou confirmar o prato"
    pratoConfirmado: false,
    preco: null,
    categoria: "Restaurante",
    bairro: "Setor 01",
    endereco: "Avenida Canaã",
    instagram: "garapeira_gastronomia",
    lat: -9.913605,
    lng: -63.0365219,
  },
  {
    slug: "consolinis-bistro-bar",
    nome: "Consolini's Bistrô Bar",
    prato: "Filé à parmegiana",
    pratoConfirmado: true,
    preco: null,
    categoria: "Bistrô",
    bairro: "Nova União 3",
    endereco: "Rua Presidente Castelo Branco, 2343",
    instagram: "consolinisbistrobar",
    lat: -9.8864841,
    lng: -63.0404102,
  },
  {
    slug: "grelhadus-burger-bar",
    nome: "Grelhadus Burger Bar",
    prato: "Bolinhos de cupim",
    pratoConfirmado: true,
    preco: "R$ 55 (porção com 6 unidades)",
    categoria: "Hamburgueria",
    bairro: "Setor 05",
    endereco: "Rua Minas Gerais, 3035 — subesquina com Avenida Jaru",
    instagram: "grelhadusburger_ariquemes",
    lat: -9.9046299,
    lng: -63.038175,
  },
  {
    slug: "braseiro-trevisan",
    nome: "Braseiro Trevisan Hamburgueria Artesanal",
    prato: "Braseiro Pig",
    pratoConfirmado: true,
    preco: "R$ 29,00",
    categoria: "Hamburgueria",
    bairro: "Jardim Jorge Teixeira",
    endereco: "Rua Mara, 350",
    instagram: "braseirotrevisan_ari",
    lat: -9.9221071,
    lng: -63.0431062,
  },
  {
    slug: "haus-bier",
    nome: "Haus Bier Fábrica do Chopp",
    prato: "Pirarucu à milanesa",
    pratoConfirmado: true,
    preco: null,
    categoria: "Choperia",
    bairro: "Setor 01",
    endereco: "Rua Canaã com Castanheira, 2268",
    instagram: null,
    lat: -9.9137847,
    lng: -63.0438447,
  },
  {
    slug: "restaurante-caravellas",
    nome: "Restaurante Caravellas",
    prato: "Bolinho de pirarucu", // TODO: ficha marca "ainda vou confirmar o prato"
    pratoConfirmado: false,
    preco: null,
    categoria: "Restaurante",
    bairro: "Setor 01",
    endereco: "Avenida Canaã, 3282",
    instagram: "caravellasculinaria",
    lat: -9.9135909,
    lng: -63.0360753,
  },
  {
    slug: "buck-burger",
    nome: "Buck Burger",
    prato: "Coxinha de cupim",
    pratoConfirmado: true,
    preco: null,
    categoria: "Hamburgueria",
    bairro: "Setor 03",
    endereco: "Avenida Jaru, 2917",
    instagram: "buckburgeroficial",
    lat: -9.9049497,
    lng: -63.0378326,
  },
  {
    slug: "to-de-boa",
    nome: "Tô de Boa",
    prato: "Bolinho de costela",
    pratoConfirmado: true,
    preco: null,
    categoria: "Bar",
    bairro: "Setor 03",
    endereco: "Rua Maceió, 2484",
    instagram: null,
    lat: -9.9093242,
    lng: -63.040031,
  },
  {
    slug: "cia-petiscaria",
    nome: "Cia Petiscaria",
    prato: "Bolinho de costela",
    pratoConfirmado: true,
    preco: null,
    categoria: "Petiscaria",
    bairro: "", // TODO: em branco na ficha. Preencher antes de publicar.
    endereco: "Avenida Tancredo Neves, 2619",
    instagram: "ciapetiscariaariquemes",
    lat: -9.9078556,
    lng: -63.034691,
  },
  {
    slug: "imperio-petiscaria",
    nome: "Império Petiscaria",
    prato: "Costelinha de tambaqui",
    pratoConfirmado: true,
    preco: null,
    categoria: "Petiscaria",
    bairro: "Setor 05",
    endereco: "Avenida Guaporé, 3621",
    instagram: "imperiopetiscaria",
    lat: -9.8990396,
    lng: -63.0361045,
  },
  {
    slug: "bar-do-fuba",
    nome: "Bar do Fubá",
    prato: "Bolinho de carne",
    pratoConfirmado: true,
    preco: null,
    categoria: "Bar",
    bairro: "Setor 01",
    endereco: "Avenida Canaã, 2064",
    instagram: "bardofuba",
    lat: -9.9138212,
    lng: -63.0459208,
  },
  {
    slug: "buteco-fnm",
    nome: "Buteco F.N.M",
    prato: "Bolinho de costela",
    pratoConfirmado: true,
    preco: null,
    categoria: "Bar",
    bairro: "Setor 06",
    endereco: "Rua Olavo Bilac, 3197",
    instagram: null,
    lat: -9.9021609,
    lng: -63.0314903,
  },
];
